# Markdown TOC Generator Configuration

# Header levels to include (1-6)
# Default is [2], which captures only H2 headers
header_levels: [2, 3]

# Title for the Table of Contents section
# Default is '## Contents'
toc_title: '## Contents'

# Indentation style ('github' or 'nested')
# Default is 'github'
indent_style: 'nested'
